version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: skillhub-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - skillhub-network

  # Backend API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: skillhub-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/skillhub?authSource=admin
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    volumes:
      - backend_uploads:/app/uploads
    networks:
      - skillhub-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: skillhub-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - skillhub-network

volumes:
  mongodb_data:
  backend_uploads:

networks:
  skillhub-network:
    driver: bridge 